<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/7/14
 * Time: 8:42
 */
class FinancePoolMoney extends FinancePool
{
    public function __construct($_sDealerNo, $sRelationNo)
    {
        parent::__construct($_sDealerNo, $sRelationNo); // TODO: Change the autogenerated stub
    }

    public function increaseTotalMoney($dMoney){
        parent::increase("dTotalMoney",$dMoney,"TOTAL_MONEY");
    }

    public function decreaseTotalMoney($dMoney){
        parent::decrease("dTotalMoney",$dMoney,"TOTAL_MONEY");
    }

    public function increaseLockedMoney($dMoney){
        parent::increase("dLockedMoney",$dMoney,"LOCKED_MONEY");
    }

    public function decreaseLockedMoney($dMoney){
        parent::decrease("dLockedMoney",$dMoney,"LOCKED_MONEY");
    }

}