<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/7/14
 * Time: 8:44
 */
class FinancePoolTax extends FinancePool
{
    public function __construct($_sDealerNo, $sRelationNo)
    {
        parent::__construct($_sDealerNo, $sRelationNo); // TODO: Change the autogenerated stub
    }


    public function increaseReturnTax($dTax){
        parent::increase("dReturnTax",$dTax,"RETURN_TAX");
    }

    public function decreaseReturnTax($dTax){
        parent::decrease("dReturnTax",$dTax,"RETURN_TAX");
    }

    public function increaseAddTax($dTax){
        parent::increase("dAddTax",$dTax,"ADD_TAX");
    }

    public function decreaseAddTax($dTax){
        parent::decrease("dAddTax",$dTax,"ADD_TAX");
    }
}