<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/8/26
 * Time: 17:30
 */
class Model_Table_BusFinanceTaxDetail extends Model_Table
{
    function fetchRecord($iStart = '', $iLimit = '')
    {
        $iStart = $iLimit="";
        return parent::fetchRecord($iStart, $iLimit); // TODO: Change the autogenerated stub
    }

    function genSqlWhere_Search()
    {
        $arrSearch = parent::genSqlWhere_Search();
        if(!empty($_GET['Id'])) $arrSearch[] = "iTaxPk={$_GET['Id']}";
        return $arrSearch;
    }

}