<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/8/8
 * Time: 14:00
 */
class Model_Table_BusFinancePaymentDetail extends Model_Table
{
    function fetchRecord($iStart = '', $iLimit = '')
    {
        $iStart = $iLimit="";
        return parent::fetchRecord($iStart, $iLimit); // TODO: Change the autogenerated stub
    }

    function genSqlWhere_Search()
    {
        $arrSearch = parent::genSqlWhere_Search();
        if(!empty($_GET['Id'])) $arrSearch[] = "iPaymentPk={$_GET['Id']}";
        return $arrSearch;
    }


}