<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/8/8
 * Time: 16:41
 */
class Model_Submit_BusFinanceTax extends Model_Submit
{
    function beforeFormSave($iId)
    {
        $sMonth = $_POST["sMonth"];

        $sSql = "Select count(*) As iCount From bus_finance_payment Where iStatus=1 and DATE_FORMAT(dtCreateTime,'%Y-%m')='{$sMonth}'";
        $arrRecords = $this->getDb()->select($sSql);
        if($arrRecords[0]["iCount"] == 0){
            return array (
                'status' => 'error',
                'message' => "{$sMonth}没有发放记录或发放记录未导入发放结果，无法计算税金！"
            );
        }

        $sSql ="Select count(*) As iCount From bus_finance_tax Where sMonth='{$sMonth}' And iSysDelete=0";
        $arrRecords = $this->getDb()->select($sSql);
        if($arrRecords[0]["iCount"] == 1){
            return array (
                'status' => 'error',
                'message' => "{$sMonth}税金已生成，无法重复添加！"
            );
        }



        return true;
    }

    function afterFormSave($iId)
    {
        $oFTax = new FinanceTax();
        $oFTax->createFinanceTax($iId);
        parent::afterFormSave($iId); // TODO: Change the autogenerated stub
    }

    function beforeDelete($iId)
    {
        $oFPTax = new FinanceTax();
        return $oFPTax->deleteFinanceTax($iId);
    }
}