<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/8/8
 * Time: 17:05
 */
class Model_Form_BusFinanceTax extends Model_Form
{
    function fetchField()
    {
        $arrDisplayField = array("iPk", "sNo", "sMonth");
        $arrFieldTemp = parent::fetchField(); // TODO: Change the autogenerated stub
        foreach($arrFieldTemp as $v){
            if(in_array($v['name'],$arrDisplayField))
                $arrField[] = $v;
        }
        return $arrField;
    }
}