<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/7/7
 * Time: 17:23
 */
class Model_Submit_BusFinancePayment extends Model_Submit
{
    function __construct($sModel, $sApp)
    {
        parent::__construct($sModel, $sApp); // TODO: Change the autogenerated stub
    }

    function beforeFormSave($iId)
    {
        $oFPayment = new FinancePayment();
        $arrUsableBonus = $oFPayment->fetchUsableBonus();
        $iCount1 = count($arrUsableBonus);

        $sSql = "Select count(*) As iCount From bus_finance_tax Where iSysConfirmFlag=0 and iSysDelete=0";
        $arrRecord = $this->getDb()->select($sSql);
        $iCount2 = $arrRecord[0]["iCount"];

        if($iCount1==0){
            return array (
                'status' => 'error',
                'message' => '奖金池中无可用奖金！'
            );
        }else if($iCount2!=0){
            return array (
                'status' => 'error',
                'message' => '有未审核税金管理，请审核后在进行奖金发放！'
            );
        }else{
            return true;
        }
    }


    function afterFormSave($iId)
    {//添加增加发放期相关代码，包括计算发放人数，钱数
        $oFPayment = new FinancePayment();
        $oFPayment->createPayment($iId);
        parent::afterFormSave($iId); // TODO: Change the autogenerated stub

    }

    function beforeDelete($iId)
    {
        $oFPayment = new FinancePayment();
        return $oFPayment->deletePayment($iId);
    }
}