<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/7/7
 * Time: 17:02
 */
class Model_Form_BusFinancePayment extends Model_Form
{
    function __construct($sModel, $sApp) {
        parent::__construct($sModel, $sApp);
    }

    function fetchField()
    {
        $arrDisplayField = array("iPk", "sNo", "sMemo");
        $arrFieldTemp = parent::fetchField(); // TODO: Change the autogenerated stub
        foreach($arrFieldTemp as $v){
            if(in_array($v['name'],$arrDisplayField))
                $arrField[] = $v;
        }
        return $arrField;
    }


}