<?php

/**
 * Created by PhpStorm.
 * User: jinli
 * Date: 2016/7/21
 * Time: 15:40
 */
class Page_ExportDetail_BusFinancePayment extends Page
{
    function __construct($sClassType, $sApp)
    {
        parent::__construct($sClassType, $sApp); // TODO: Change the autogenerated stub
    }

    function show()
    {
        $iPaymentPk = $_GET["Id"];
        $sSql = "Select sNo From bus_finance_payment Where iPk='$iPaymentPk'";
        $arrRecord = $this->getDb()->select($sSql);
        $sPaymentNo = $arrRecord[0]["sNo"];

        $sFileName = "bonus_payment";
        $arrHeader = array("发放序号","顾客号","姓名","身份证","银行名称","账号","金额");
        $sSql = "Select concat('$sPaymentNo-',iPk) As sNo,sDealerNo, '' As sName, '' As sId, '' As sBank, '' As sAccount,dTotal From bus_finance_payment_detail Where iPaymentPk='$iPaymentPk'";

        $arrRecord = $this->getDb()->select($sSql);

        $oExcel = new Excel();
        $oExcel->setSFileName($sFileName);
        $oExcel->setArrHeader($arrHeader);
        $oExcel->setArrRecord($arrRecord);
        $oExcel->outPutXls();
    }


}